[2025-07-22T18:09:07.331+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T18:09:07.352+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_data_pipeline.run_spark_job_container manual__2025-07-22T18:09:05.414363+00:00 [queued]>
[2025-07-22T18:09:07.358+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_data_pipeline.run_spark_job_container manual__2025-07-22T18:09:05.414363+00:00 [queued]>
[2025-07-22T18:09:07.359+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-22T18:09:07.370+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_spark_job_container> on 2025-07-22 18:09:05.414363+00:00
[2025-07-22T18:09:07.376+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1391) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-22T18:09:07.378+0000] {standard_task_runner.py:63} INFO - Started process 1393 to run task
[2025-07-22T18:09:07.377+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_data_pipeline', 'run_spark_job_container', 'manual__2025-07-22T18:09:05.414363+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/flight_pipeline_dag.py', '--cfg-path', '/tmp/tmpnkr7htq1']
[2025-07-22T18:09:07.380+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask run_spark_job_container
[2025-07-22T18:09:07.422+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_data_pipeline.run_spark_job_container manual__2025-07-22T18:09:05.414363+00:00 [running]> on host d77a53274a34
[2025-07-22T18:09:07.502+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_data_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_job_container' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T18:09:05.414363+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-22T18:09:05.414363+00:00'
[2025-07-22T18:09:07.504+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T18:09:07.520+0000] {docker.py:366} INFO - Starting docker container from image realtime-flight-pipeline/spark-job:0.5
[2025-07-22T18:09:07.524+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-07-22T18:09:07.802+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m18:09:07.80 [0m[38;5;2mINFO [0m ==>
[2025-07-22T18:09:07.803+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m18:09:07.80 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2025-07-22T18:09:07.804+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m18:09:07.80 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-07-22T18:09:07.806+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m18:09:07.80 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-07-22T18:09:07.807+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m18:09:07.80 [0m[38;5;2mINFO [0m ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit [1mhttps://bitnami.com/enterprise[0m
[2025-07-22T18:09:07.808+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m18:09:07.80 [0m[38;5;2mINFO [0m ==>
[2025-07-22T18:09:07.810+0000] {docker.py:436} INFO - 
[2025-07-22T18:09:09.512+0000] {docker.py:436} INFO - Traceback (most recent call last):
  File "/app/process_flights.py", line 32, in <module>
    main()
  File "/app/process_flights.py", line 14, in main
    spark = SparkSession.builder \
            ^^^^^^^^^^^^
NameError: name 'SparkSession' is not defined
[2025-07-22T18:09:09.513+0000] {docker.py:436} INFO - 
[2025-07-22T18:09:09.524+0000] {docker.py:436} INFO - 25/07/22 18:09:09 INFO ShutdownHookManager: Shutdown hook called
[2025-07-22T18:09:09.527+0000] {docker.py:436} INFO - 25/07/22 18:09:09 INFO ShutdownHookManager: Deleting directory /tmp/spark-8e651b66-e909-4c8a-8243-c78e70ad8ccc
[2025-07-22T18:09:10.012+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T18:09:10.020+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.49/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 440, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 457, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.49/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpx9d_6g4y")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 380, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 444, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-22T18:09:10.024+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=flight_data_pipeline, task_id=run_spark_job_container, run_id=manual__2025-07-22T18:09:05.414363+00:00, execution_date=20250722T180905, start_date=20250722T180907, end_date=20250722T180910
[2025-07-22T18:09:10.034+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task run_spark_job_container (Docker container failed: {'StatusCode': 1}; 1393)
[2025-07-22T18:09:10.081+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-22T18:09:10.094+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-22T18:09:10.096+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
